apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cntr-multitool
  labels:
    app: test-cntr-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cntr-multitool
  template:
    metadata:
      labels:
        app: test-cntr-multitool
    spec:
      containers:
      - name: test-cntr-multitool
        image: tse77/cntr-multitool
        command: [./api]
        securityContext:
          privileged: true
        args:
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: MY_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: MY_CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: test-cntr-multitool
                resource: requests.cpu
          - name: MY_CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: test-cntr-multitool
                resource: limits.cpu
          - name: MY_MEM_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: test-cntr-multitool
                resource: requests.memory
          - name: MY_MEM_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: test-cntr-multitool
                resource: limits.memory
---
apiVersion: v1
kind: Service
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  type: NodePort
  selector: multitool
  ports:
    - port: 9100
  selector:
    app: multitool
